import { useState } from 'react';
import { X, Receipt, Calculator } from 'lucide-react';
import { db } from '@/lib/db/database';
import { useAuthStore } from '@/stores/authStore';
import { createOperation } from '@/lib/db/repositories/operations';
import { createAuditEvent } from '@/lib/db/repositories/auditEvents';
import { syncManager } from '@/lib/sync/syncManager';
import type { Inspection, Invoice } from '@/types/db';

interface InvoiceGenerationModalProps {
  isOpen: boolean;
  onClose: () => void;
  inspection: Inspection;
  onInvoiceCreated: (invoice: Invoice) => void;
}

export default function InvoiceGenerationModal({
  isOpen,
  onClose,
  inspection,
  onInvoiceCreated,
}: InvoiceGenerationModalProps) {
  const { user } = useAuthStore();

  const [labourCharges, setLabourCharges] = useState<number>(650);
  const [partsCharges, setPartsCharges] = useState<number>(350);
  const [travelCharges, setTravelCharges] = useState<number>(150);
  const [otherCharges, setOtherCharges] = useState<number>(0);
  const [discount, setDiscount] = useState<number>(0);
  const [notes, setNotes] = useState<string>('Standard on-site diagnostic, component test & maintenance.');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Computations
  const subtotal = Math.max(
    0,
    Number(labourCharges) + Number(partsCharges) + Number(travelCharges) + Number(otherCharges) - Number(discount)
  );
  const taxPercent = 18; // Standard GST
  const taxAmount = Number(((subtotal * taxPercent) / 100).toFixed(2));
  const grandTotal = Number((subtotal + taxAmount).toFixed(2));

  if (!isOpen) return null;

  const handleGenerateInvoice = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;

    setIsSubmitting(true);
    try {
      const invoiceId = crypto.randomUUID();
      const now = new Date().toISOString();
      const invoiceNumber = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;

      // Standard Indian UPI merchant format
      const upiMerchantVpa = 'fieldsync@icici';
      const merchantName = encodeURIComponent('FieldSync Industrial Services');
      const noteParam = encodeURIComponent(`Bill ${invoiceNumber}`);
      const qrPayload = `upi://pay?pa=${upiMerchantVpa}&pn=${merchantName}&am=${grandTotal}&tr=${invoiceNumber}&tn=${noteParam}&cu=INR`;

      const newInvoice: Invoice = {
        id: invoiceId,
        invoiceNumber,
        inspectionId: inspection.id,
        inspectionTitle: inspection.title,
        customerId: inspection.customerId,
        customerName: inspection.reportedBy || 'Valued Client',
        customerEmail: inspection.customerEmail,
        customerPhone: inspection.customerPhone,
        technicianId: user.id,
        technicianName: user.fullName || 'Field Technician',
        labourCharges: Number(labourCharges),
        partsCharges: Number(partsCharges),
        travelCharges: Number(travelCharges),
        otherCharges: Number(otherCharges),
        discount: Number(discount),
        taxPercent,
        taxAmount,
        subtotal,
        grandTotal,
        status: 'PAYMENT_PENDING',
        qrPayload,
        notes: notes.trim() || undefined,
        createdAt: now,
        updatedAt: now,
        syncStatus: 'PENDING',
      };

      await db.invoices.put(newInvoice);

      await createOperation({
        userId: user.id,
        inspectionId: inspection.id,
        entityType: 'invoice',
        entityId: invoiceId,
        operationType: 'CREATE',
        payload: {
          id: invoiceId,
          invoiceNumber,
          inspectionId: inspection.id,
          customerName: newInvoice.customerName,
          grandTotal,
          status: 'PAYMENT_PENDING',
          qrPayload,
        },
      });

      await createAuditEvent({
        userId: user.id,
        userName: user.fullName,
        inspectionId: inspection.id,
        entityType: 'INVOICE',
        entityId: invoiceId,
        action: 'CREATED',
        field: 'invoiceGeneration',
        afterValue: `Invoice #${invoiceNumber} for ₹${grandTotal} generated by ${user.fullName}`,
      });

      onInvoiceCreated(newInvoice);
      void syncManager.syncNow();
      onClose();
    } catch (err) {
      console.error('Failed to generate invoice:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-zinc-900/80 backdrop-blur-sm animate-fade-in">
      <div className="bg-white rounded-3xl max-w-lg w-full overflow-hidden shadow-2xl border border-zinc-200 flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-zinc-100 flex items-center justify-between bg-zinc-50/50">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-2xl bg-indigo-600 text-white flex items-center justify-center shadow-sm shadow-indigo-200">
              <Receipt size={18} />
            </div>
            <div>
              <h3 className="text-sm font-bold text-zinc-900">Generate Work Invoice</h3>
              <p className="text-[11px] text-zinc-500">Record billable items and generate QR code</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full border border-zinc-200 hover:bg-zinc-100 flex items-center justify-center text-zinc-500 cursor-pointer transition-colors"
          >
            <X size={16} />
          </button>
        </div>

        {/* Content Body */}
        <form onSubmit={handleGenerateInvoice} className="p-5 overflow-y-auto space-y-4 text-xs">
          {/* Work Order Info */}
          <div className="p-3 bg-zinc-50 rounded-2xl border border-zinc-200 space-y-1">
            <div className="flex justify-between font-medium">
              <span className="text-zinc-500">Service Ticket:</span>
              <span className="font-bold text-zinc-900 truncate max-w-[240px]">
                {inspection.title}
              </span>
            </div>
            <div className="flex justify-between font-medium">
              <span className="text-zinc-500">Customer:</span>
              <span className="font-bold text-indigo-700">
                {inspection.reportedBy || 'Enterprise Client'}
              </span>
            </div>
          </div>

          {/* Itemized Charges Grid */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block font-semibold text-zinc-700 mb-1">Labour Charges (₹)</label>
              <input
                type="number"
                min="0"
                step="50"
                value={labourCharges}
                onChange={(e) => setLabourCharges(Number(e.target.value))}
                className="w-full h-9 px-3 rounded-xl border border-zinc-200 font-mono text-zinc-900 focus:outline-hidden focus:border-indigo-500"
                required
              />
            </div>

            <div>
              <label className="block font-semibold text-zinc-700 mb-1">Parts & Materials (₹)</label>
              <input
                type="number"
                min="0"
                step="50"
                value={partsCharges}
                onChange={(e) => setPartsCharges(Number(e.target.value))}
                className="w-full h-9 px-3 rounded-xl border border-zinc-200 font-mono text-zinc-900 focus:outline-hidden focus:border-indigo-500"
              />
            </div>

            <div>
              <label className="block font-semibold text-zinc-700 mb-1">Travel / Conveyance (₹)</label>
              <input
                type="number"
                min="0"
                step="50"
                value={travelCharges}
                onChange={(e) => setTravelCharges(Number(e.target.value))}
                className="w-full h-9 px-3 rounded-xl border border-zinc-200 font-mono text-zinc-900 focus:outline-hidden focus:border-indigo-500"
              />
            </div>

            <div>
              <label className="block font-semibold text-zinc-700 mb-1">Other Surcharges (₹)</label>
              <input
                type="number"
                min="0"
                step="50"
                value={otherCharges}
                onChange={(e) => setOtherCharges(Number(e.target.value))}
                className="w-full h-9 px-3 rounded-xl border border-zinc-200 font-mono text-zinc-900 focus:outline-hidden focus:border-indigo-500"
              />
            </div>
          </div>

          <div>
            <label className="block font-semibold text-zinc-700 mb-1">Special Discount (₹)</label>
            <input
              type="number"
              min="0"
              step="50"
              value={discount}
              onChange={(e) => setDiscount(Number(e.target.value))}
              className="w-full h-9 px-3 rounded-xl border border-zinc-200 font-mono text-zinc-900 focus:outline-hidden focus:border-indigo-500"
            />
          </div>

          <div>
            <label className="block font-semibold text-zinc-700 mb-1">Service & Invoicing Notes</label>
            <textarea
              rows={2}
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              className="w-full p-2.5 rounded-xl border border-zinc-200 focus:outline-hidden focus:border-indigo-500 resize-none text-xs"
            />
          </div>

          {/* Real-time Calculation Summary Card */}
          <div className="p-4 rounded-2xl bg-indigo-50/70 border border-indigo-100 space-y-1.5 font-medium">
            <div className="flex justify-between text-zinc-600">
              <span>Subtotal:</span>
              <span className="font-mono font-bold text-zinc-900">₹{subtotal.toFixed(2)}</span>
            </div>
            <div className="flex justify-between text-zinc-600">
              <span>Tax (GST @ {taxPercent}%):</span>
              <span className="font-mono font-bold text-zinc-900">₹{taxAmount.toFixed(2)}</span>
            </div>
            <div className="flex justify-between text-sm font-bold text-indigo-950 pt-1.5 border-t border-indigo-200/60">
              <span>Grand Total:</span>
              <span className="font-mono text-base font-black text-indigo-600">
                ₹{grandTotal.toFixed(2)}
              </span>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-2 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 h-10 rounded-xl border border-zinc-200 font-bold text-zinc-700 hover:bg-zinc-50 cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting || grandTotal <= 0}
              className="flex-1 h-10 rounded-xl bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white font-bold flex items-center justify-center gap-1.5 shadow-sm shadow-indigo-100 cursor-pointer"
            >
              <Calculator size={14} />
              {isSubmitting ? 'Generating…' : 'Generate & Issue Invoice'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
